/**
 * Created by DzEN on 29.01.2017.
 */
import { fork } from 'redux-saga/effects';
import { saga as appPageSaga } from 'client/pages/App';
import { saga as loginPageSaga } from 'client/pages/LoginPage';
import { saga as registerPageSaga } from 'client/pages/RegisterPage';
import { saga as registerCheckLanguageSaga } from 'client/components/dialogs/languageSelect/DialogCheckLanguage';
import { saga as farmsPageSaga } from 'client/pages/FarmsPage';
import { saga as groupsPageSaga } from 'client/pages/GroupsPage';
import { saga as ingredientsPageSaga } from 'client/pages/IngredientsPage';
import { saga as dialogIngredientAddSaga } from 'client/components/dialogs/ingredients/DialogIngredientsAdd';
import { saga as dialogIngredientEditSaga } from 'client/components/dialogs/ingredients/DialogIngredientsEdit';
import { saga as dialogIngredientRemoveSaga } from 'client/components/dialogs/ingredients/DialogIngredientsRemove';
import { saga as transfersPageSaga } from 'client/pages/TransfersPage';
import { saga as sideMenuSaga } from 'client/components/SideMenu';
import { saga as adminSideMenuSaga } from 'client/components/AdminSideMenu';
import { saga as dialogFarmsAddSaga } from 'client/components/dialogs/farms/DialogFarmsAdd';
import { saga as dialogFarmsEditSaga } from 'client/components/dialogs/farms/DialogFarmsEdit';
import { saga as dialogFarmsRemoveSaga } from 'client/components/dialogs/farms/DialogFarmsRemove';
import { saga as dialogGroupAddSaga } from 'client/components/dialogs/groups/DialogGroupsAdd';
import { saga as dialogGroupEditSaga } from 'client/components/dialogs/groups/DialogGroupsEdit';
import { saga as dialogGroupRemoveSaga } from 'client/components/dialogs/groups/DialogGroupsRemove';
import { saga as dialogTransferAddSaga } from 'client/components/dialogs/transfer/DialogTransferAdd';
import { saga as dialogTransferTypeAddSaga } from 'client/components/dialogs/transfer/DialogTransferTypeAdd';
import { saga as deliveryPageSaga } from 'client/pages/DeliveryPage';
import { saga as dialogDeliveryAddSaga } from 'client/components/dialogs/deliveries/DialogDeliveryAdd';
import { saga as dialogDeliveryEditSaga } from 'client/components/dialogs/deliveries/DialogDeliveryEdit';
import { saga as dialogDeliveryRemoveSaga } from 'client/components/dialogs/deliveries/DialogDeliveryRemove';
import { saga as stocksPageSaga } from 'client/pages/StocksPage';
import { saga as rationsPageSaga } from 'client/pages/RationsPage';
import { saga as rationPageSaga } from 'client/pages/RationPage';
import { saga as dialogRationRemove } from 'client/components/dialogs/rations/DialogRationsRemove';
import { saga as dialogRationLoadingCountsTable } from 'client/components/tables/TableRationLoadingCounts';
import { saga as dialogRationIngredientsTable } from 'client/components/tables/TableRationIngredients';
import { saga as dialogRationGroupsTable } from 'client/components/tables/TableRationGroups';
import { saga as schedulesPageSaga } from 'client/pages/SchedulesPage';
import { saga as dialogScheduleRemoveSaga } from 'client/components/dialogs/schedules/DialogSchedulesRemove';
import { saga as dialogScheduleAddSaga } from 'client/components/dialogs/schedules/DialogSchedulesAdd';
import { saga as schedulePageSaga } from 'client/pages/SchedulePage';
import { saga as scheduleRationLoadingCountTableSaga } from 'client/components/tables/TableScheduleRationLoadingCounts';
import { saga as mixersPageSaga } from 'client/pages/MixersPage';
import { saga as dialogMixersAddSaga } from 'client/components/dialogs/mixers/DialogMixersAdd';
import { saga as dialogMixersEditSaga } from 'client/components/dialogs/mixers/DialogMixersEdit';
import { saga as dialogMixersRemoveSaga } from 'client/components/dialogs/mixers/DialogMixersRemove';
import { saga as customersPageSaga } from 'client/pages/CustomersPage';
import { saga as dialogCustomerAddSaga } from 'client/components/dialogs/customers/DialogCustomerAdd';
import { saga as dialogCustomerEditSaga } from 'client/components/dialogs/customers/DialogCustomerEdit';
import { saga as dialogCustomerRemoveSaga } from 'client/components/dialogs/customers/DialogCustomerRemove';
import { saga as userGroupsPageSaga } from 'client/pages/UserGroupsPage';
import { saga as dialogUserGroupsAddSaga } from 'client/components/dialogs/usergroups/DialogUserGroupsAdd';
import { saga as dialogUserGroupsEditSaga } from 'client/components/dialogs/usergroups/DialogUserGroupsEdit';
import { saga as dialogUserGroupsRemoveSaga } from 'client/components/dialogs/usergroups/DialogUserGroupsRemove';
import { saga as dialogUserGroupsEditPermissionsSaga } from
  'client/components/dialogs/usergroups/DialogUserGroupsEditPermissions';
import { saga as loadingCountsPageSaga } from 'client/pages/LoadingCountsPage';
import { saga as dialogLoadingCountsAddSaga } from 'client/components/dialogs/loadingcounts/DialogLoadingCountsAdd';
import { saga as dialogLoadingCountsEditSaga } from 'client/components/dialogs/loadingcounts/DialogLoadingCountsEdit';
import { saga as dialogLoadingCountsRemoveSaga } from 'client/components/dialogs/loadingcounts/DialogLoadingCountsRemove';
import { saga as historyPageSaga } from 'client/pages/HistoryPage';
import { saga as animalfeedsPageSaga } from 'client/pages/AnimalfeedsPage';
import { saga as dialogAnimalfeedsAddSaga } from 'client/components/dialogs/animalfeeds/DialogAnimalfeedsAdd';
import { saga as dialogAnimalfeedsEditSaga } from 'client/components/dialogs/animalfeeds/DialogAnimalfeedsEdit';
import { saga as dialogAnimalfeedsRemoveSaga } from 'client/components/dialogs/animalfeeds/DialogAnimalfeedsRemove';
import { saga as deliveryAnimalfeedsPageSaga } from 'client/pages/DeliveryAnimalfeedPage';
import { saga as dialogDeliveryAnimalfeedAddSaga } from
  'client/components/dialogs/deliveryanimalfeed/DialogDeliveryAnimalfeedAdd';
import { saga as dialogDeliveryAnimalfeedEditSaga } from
  'client/components/dialogs/deliveryanimalfeed/DialogDeliveryAnimalfeedEdit';
import { saga as dialogDeliveryAnimalfeedRemoveSaga } from
  'client/components/dialogs/deliveryanimalfeed/DialogDeliveryAnimalfeedRemove';
import { saga as worksheetsPageSaga } from 'client/pages/WorksheetsPage';
import { saga as dialogWorksheetsEditSaga } from 'client/components/dialogs/worksheets/DialogWorksheetsEdit';
import { saga as dialogWorksheetsRemoveSaga } from 'client/components/dialogs/worksheets/DialogWorksheetsRemove';
import { saga as reportsPageSaga } from 'client/pages/ReportsPage';
import { saga as languageProviderSaga } from 'client/containers/LanguageProvider';

export default function* mainSaga() {
  yield fork(loginPageSaga);
  yield fork(registerPageSaga);
  yield fork(registerCheckLanguageSaga);
  yield fork(languageProviderSaga);
  yield fork(appPageSaga);
  yield fork(sideMenuSaga);
  yield fork(adminSideMenuSaga);
  yield fork(farmsPageSaga);
  yield fork(dialogFarmsAddSaga);
  yield fork(dialogFarmsRemoveSaga);
  yield fork(dialogFarmsEditSaga);
  yield fork(ingredientsPageSaga);
  yield fork(dialogIngredientAddSaga);
  yield fork(dialogIngredientEditSaga);
  yield fork(dialogIngredientRemoveSaga);
  yield fork(groupsPageSaga);
  yield fork(dialogGroupAddSaga);
  yield fork(dialogGroupEditSaga);
  yield fork(dialogGroupRemoveSaga);
  yield fork(transfersPageSaga);
  yield fork(dialogTransferAddSaga);
  yield fork(dialogTransferTypeAddSaga);
  yield fork(deliveryPageSaga);
  yield fork(dialogDeliveryAddSaga);
  yield fork(dialogDeliveryEditSaga);
  yield fork(dialogDeliveryRemoveSaga);
  yield fork(stocksPageSaga);
  yield fork(rationPageSaga);
  yield fork(rationsPageSaga);
  yield fork(dialogRationRemove);
  yield fork(dialogRationLoadingCountsTable);
  yield fork(dialogRationIngredientsTable);
  yield fork(dialogRationGroupsTable);
  yield fork(schedulesPageSaga);
  yield fork(dialogScheduleRemoveSaga);
  yield fork(dialogScheduleAddSaga);
  yield fork(schedulePageSaga);
  yield fork(scheduleRationLoadingCountTableSaga);
  yield fork(mixersPageSaga);
  yield fork(dialogMixersAddSaga);
  yield fork(dialogMixersEditSaga);
  yield fork(dialogMixersRemoveSaga);
  yield fork(customersPageSaga);
  yield fork(dialogCustomerAddSaga);
  yield fork(dialogCustomerEditSaga);
  yield fork(dialogCustomerRemoveSaga);
  yield fork(userGroupsPageSaga);
  yield fork(dialogUserGroupsAddSaga);
  yield fork(dialogUserGroupsEditSaga);
  yield fork(dialogUserGroupsRemoveSaga);
  yield fork(dialogUserGroupsEditPermissionsSaga);
  yield fork(loadingCountsPageSaga);
  yield fork(dialogLoadingCountsAddSaga);
  yield fork(dialogLoadingCountsEditSaga);
  yield fork(dialogLoadingCountsRemoveSaga);
  yield fork(historyPageSaga);
  yield fork(animalfeedsPageSaga);
  yield fork(dialogAnimalfeedsAddSaga);
  yield fork(dialogAnimalfeedsEditSaga);
  yield fork(dialogAnimalfeedsRemoveSaga);
  yield fork(deliveryAnimalfeedsPageSaga);
  yield fork(dialogDeliveryAnimalfeedAddSaga);
  yield fork(dialogDeliveryAnimalfeedEditSaga);
  yield fork(dialogDeliveryAnimalfeedRemoveSaga);
  yield fork(worksheetsPageSaga);
  yield fork(dialogWorksheetsEditSaga);
  yield fork(dialogWorksheetsRemoveSaga);
  yield fork(reportsPageSaga);
}
